### ISSUE TITLE
I can't run metaprob2

### ISSUE THREAD

**Issue by esraagithub** [frankandreace/metaprob2#1]
Hello
I am a biologist i  have a problem in running metaprob2. 

I followed all instructions in this link: https://github.com/frankandreace/metaprob2

when i write this code i get "permission denied"
./METAPROB2.sh -h
bash: ./METAPROB2.sh: Permission denied
 
also i couldn't find "METAPROB2" file in any directory  so i couldn't run the program using ./METAPROB2 ......  like this example:
./METAPROB2 -s[number of expected species/genera]-c[minimum chain score] -t[number of cores to be used]-l <fasta/fastq input file> <output files name>
but it run with this code  ./MetaProb ..... but it gave me "Killed" at the end 
N. Cluster: 0
Parameter q: 30
Parameter m: 5
Parameter SeedSize: 9000
Parameter lmerfreq: 4
Parameter Kmeans iteration max: 100
Norm: D2star_All_Read_Prob_Lmer_Euclidian
Graph Type: Paired
Loading Sequences... Complete
Loaded sequences: 23744520
Extract q-mer from Sequences... Killed

**Comment by frankandreace** [comment]
Hi, try this: go to the directory where METRAPROB2.sh is and execute 'chmod +x METRAPROB2.sh'. This should fix your problem. You can also avoid this passage by running 'sh  METRAPROB2.sh'  instead of './METAPROB2.sh' and it should work.

You get kill message because MetaProb is a C++ tool that does not accept arguments as the METAPROB2 pipeline does.
It is not the same thing. METAPROB2 pipeline has several steps before MetaProb to increase its performance. To have a look at MetaProb manual, please visit https://bitbucket.org/samu661/metaprob/src/master/. Be aware that the source code provided there is not longer maintained and it was not working for me, so use directly the one I provide in this repo.

Let me know if it works!

**Comment by esraagithub** [comment]
> Hi, try this: go to the directory where METRAPROB2.sh is and execute 'chmod +x METRAPROB2.sh'. This should fix your problem. You can also avoid this passage by running 'sh METRAPROB2.sh' instead of './METAPROB2.sh' and it should work.
> 
> You get kill message because MetaProb is a C++ tool that does not accept arguments as the METAPROB2 pipeline does. It is not the same thing. METAPROB2 pipeline has several steps before MetaProb to increase its performance. To have a look at MetaProb manual, please visit https://bitbucket.org/samu661/metaprob/src/master/. Be aware that the source code provided there is not longer maintained and it was not working for me, so use directly the one I provide in this repo.
> 
> Let me know if it works!

that really help 
i did **'chmod +x METRAPROB2.sh'** then i run **./METAPROB2.sh** then the following code
 ./METAPROB2.sh -t 8 ../trimmomatic_result/sample2merged.fasta ../metaprob_result metaprob_bin


note: running **'sh METAPROB2.sh'** reulted in this error:
 METAPROB2.sh: 85: [[: not found
METAPROB2.sh: 93: Bad substitution

 i modified MINIMAP2,MINIASM, metaprob, python and  conda env directories too
but i got that error at the end:


(base) root@vmi815190:~/esraa# screen -r 913146
[detached from 913146.pts-0.vmi815190]
(base) root@vmi815190:~/esraa# screen -r 913146
[detached from 913146.pts-0.vmi815190]
(base) root@vmi815190:~/esraa# screen -r 913146
[M::main] ===> Step 4.5: aggressively cutting short overlaps <===
[M::asg_arc_del_short] removed 0 short overlaps
[M::main] ===> Step 5: generating unitigs <===
[M::main] Version: 0.3-r179
[M::main] CMD: ../miniasm/miniasm -12 -m1 -g10000 -o1 -d1 -I0.00001 -s1 -i0.00001 -d10000 -F0.01 -c0 -e0 -n0 -r0.011,0.01 -f ../trimmomatic_result/sample2merged.fasta ../metaprob_result/metaprob2_tmp/metaprob_bin.paf
[M::main] Real time: 1440.677 sec; CPU: 1428.775 sec
./count_reads.sh: 12: [: ./trimmomatic_result/sample2merged.fasta: unexpected operator
./count_reads.sh: 22: [: p: unexpected operator
./METAPROB2.sh: line 129: source: ../miniconda3: is a directory
[METAPROB2.sh] Running COMMUNITY DETECTION
Traceback (most recent call last):
  File "/root/esraa/metaprob2/.//community_detection_clear.py", line 14, in <module>
    from sknetwork.clustering import Louvain
  File "/root/esraa/miniconda3/lib/python3.9/site-packages/sknetwork/__init__.py", line 9, in <module>
    import sknetwork.topology
  File "/root/esraa/miniconda3/lib/python3.9/site-packages/sknetwork/topology/__init__.py", line 2, in <module>
    from sknetwork.topology.kcliques import Cliques
  File "sknetwork/topology/kcliques.pyx", line 1, in init sknetwork.topology.kcliques
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
[METAPROB2.sh] Running METAPROB

Fail to open: ../metaprob_result/metaprob2_tmp/metaprob_bin.fasta

**Comment by esraagithub** [comment]
> Hi, try this: go to the directory where METRAPROB2.sh is and execute 'chmod +x METRAPROB2.sh'. This should fix your problem. You can also avoid this passage by running 'sh METRAPROB2.sh' instead of './METAPROB2.sh' and it should work.
> 
> You get kill message because MetaProb is a C++ tool that does not accept arguments as the METAPROB2 pipeline does. It is not the same thing. METAPROB2 pipeline has several steps before MetaProb to increase its performance. To have a look at MetaProb manual, please visit https://bitbucket.org/samu661/metaprob/src/master/. Be aware that the source code provided there is not longer maintained and it was not working for me, so use directly the one I provide in this repo.
> 
> Let me know if it works!


that really help 
i modified directories of  MINIMAP2, MINIASM, metaprob,python and conda env to my own paths
i run **chmod +x METRAPROB2.sh** then **./METRAPROB2.sh** 

note: running 'sh METRAPROB2.sh' result into the following error:
METAPROB2.sh: 85: [[: not found
METAPROB2.sh: 93: Bad substitution


then i run this code: ./METAPROB2.sh -t 8 ../trimmomatic_result/sample2merged.fasta ../metaprob_result metaprob_bin
i got the following error at the end:

[M::main] ===> Step 4.5: aggressively cutting short overlaps <===
[M::asg_arc_del_short] removed 0 short overlaps
[M::main] ===> Step 5: generating unitigs <===
[M::main] Version: 0.3-r179
[M::main] CMD: ../miniasm/miniasm -12 -m1 -g10000 -o1 -d1 -I0.00001 -s1 -i0.00001 -d10000 -F0.01 -c0 -e0 -n0 -r0.011,0.01 -f ../trimmomatic_result/sample2merged.fasta ../metaprob_result/metaprob2_tmp/metaprob_bin.paf
[M::main] Real time: 1440.677 sec; CPU: 1428.775 sec
./count_reads.sh: 12: [: ./trimmomatic_result/sample2merged.fasta: unexpected operator
./count_reads.sh: 22: [: p: unexpected operator
./METAPROB2.sh: line 129: source: ../miniconda3: is a directory
[METAPROB2.sh] Running COMMUNITY DETECTION
Traceback (most recent call last):
File "/root/esraa/metaprob2/.//community_detection_clear.py", line 14, in
from sknetwork.clustering import Louvain
File "/root/esraa/miniconda3/lib/python3.9/site-packages/sknetwork/init.py", line 9, in
import sknetwork.topology
File "/root/esraa/miniconda3/lib/python3.9/site-packages/sknetwork/topology/init.py", line 2, in
from sknetwork.topology.kcliques import Cliques
File "sknetwork/topology/kcliques.pyx", line 1, in init sknetwork.topology.kcliques
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
[METAPROB2.sh] Running METAPROB

Fail to open: ../metaprob_result/metaprob2_tmp/metaprob_bin.fasta
